// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ProfileController from "./profile_controller"
application.register("profile", ProfileController)

import MapController from "./map_controller"
application.register("map", MapController)
